#!/usr/bin/perl

# Sreview, a web-based video review and transcoding system
# Copyright (c) 2016-2017, Wouter Verhelst <w@uter.be>
#
# Sreview is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

use strict;
use warnings;

use DBI;

our $config;
require './config.pl';

my $dbh = DBI->connect($config->{dbistring}, '', '') or die "Cannot connect to database!";

$dbh->begin_work;

my $talkid = $ARGV[0];

my $talkslug = $dbh->prepare("SELECT eventid, event, room, starttime::date AS startdate, slug FROM talk_list WHERE id = ?");

$talkslug->execute($talkid);

my $row = $talkslug->fetchrow_hashref();

my $outdirsub = $config->{outputdir};
my $outputdir = &$outdirsub($row->{event}, $row->{room}, $row->{startdate});

my $room = $row->{room};
my $slug = $row->{slug};

foreach my $suffix('.mp4', '-post.mp4', '-post.png', '-pre.mp4', '-pre.png') {
	my $building = substr($room, 0, 1);
	unlink(join('/', ($config->{pubdir}, $row->{eventid}, $building, $row->{slug} . $suffix)));
}
system("rsync -zavHP --remove-source-files $outputdir/$slug.mp4 $outputdir/$slug.vp8.webm video\@video.fosdem.org:$room/");

my $update = $dbh->prepare("UPDATE talks SET state = state_next(state) WHERE id = ? AND state = 'uploading'");
$update->execute($talkid);

$dbh->commit;
