#!/usr/bin/perl -w

use strict;
use warnings;

use SReview::Talk;
use SReview::Config::Common;
use SReview::Files::Factory;
use DBI;

my $talkid = shift;
my $config = SReview::Config::Common::setup();
my $talk = SReview::Talk->new(talkid => $talkid);
my $input = SReview::Files::Factory->create("input", $config->get("inputglob"));
die "talk not in correct stream" unless $talk->active_stream eq 'injected';
my $db = DBI->connect($config->get("dbistring"), '', '') or die "Cannot connect to database!";
my $st = $db->prepare("SELECT filename FROM raw_files WHERE room = ? AND stream = ? AND filename LIKE ?");
$st->execute($talk->roomid, $talk->active_stream, '%' . $talk->slug . '%');
my $row = $st->fetchrow_arrayref;
my $inputfile = $input->get_file(fullname => $row->[0]);
system("sreview-inject", "-t", $talkid, "-i", $input->filename);
