#!/usr/bin/perl -w

use strict;
use warnings;

use SReview::Template::SVG qw/process_template/;
use SReview::Talk;
use SReview::Config::Common;
use SReview::Files::Factory;
use DBI;

my $config = SReview::Config::Common::setup();

my $dbh = DBI->connect($config->get("dbistring"));

my $talklist = $dbh->prepare("SELECT talks.id FROM talks JOIN events ON talks.event = events.id WHERE events.name = ?");
my $rv = $talklist->execute($config->get("event"));

my %templates = ("pre" => $config->get("preroll_template"),
		 "post" => $config->get("postroll_template"),
		 "sorry" => $config->get("apology_template"));

my $coll = SReview::Files::Factory->create("intermediate", $config->get("pubdir"));

while(my $row = $rv->fetchrow_hashref) {
	my $talk = SReview::Talk->new($row->{id});
	foreach my $type("pre", "post", "sorry") {
		next unless(-f $templates{$type});
		my $relname = $talk->relative_name . "-" . $type . ".png";
		my $file = $coll->add_file(relname => $relname);
		process_template($templates{$type}, $file->filename, $talk, $config);
		$file->store_file
	}
}
